In [1]:
import pandas as pd
df = pd.read_csv('Titanic-Dataset.csv')
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [5]:
df.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis = 'columns',inplace = True)
df.head()

   Survived  Pclass     Sex   Age     Fare
0         0       3    male  22.0   7.2500
1         1       1  female  38.0  71.2833
2         1       3  female  26.0   7.9250
3         1       1  female  35.0  53.1000
4         0       3    male  35.0   8.0500

In [ ]:
# Single bracket [ ] vs Double bracket [[ ]] in Pandas & Sklearn
# df.drop() uses single brackets because it just expects a plain list of column name strings — df.drop(['col1', 'col2'], axis='columns').
# df['col'] with single brackets returns a 1D Series, which is fine for viewing data but breaks sklearn methods.
# df[['col']] with double brackets returns a 2D DataFrame, which is what sklearn's fit(), transform(), and fit_transform() always require.
# sklearn fit/transform always uses double brackets — scaler.fit_transform(df[['Age', 'Income']]) — because sklearn expects 2D input with rows as samples and columns as features.

In [19]:
target = df.Survived
inputs = df.drop('Survived',axis = 'columns')

In [20]:
dummies = pd.get_dummies(inputs.Sex)
dummies.head(3)

   female   male
0   False   True
1    True  False
2    True  False

In [21]:
inputs = pd.concat([inputs,dummies],axis='columns')
inputs.head(3)

   Pclass     Sex   Age     Fare  female   male
0       3    male  22.0   7.2500   False   True
1       1  female  38.0  71.2833    True  False
2       3  female  26.0   7.9250    True  False

In [22]:
inputs.drop('Sex',axis = 'columns',inplace = True)
inputs.head(3)

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False

In [23]:
inputs.columns[inputs.isna().any()]

Index(['Age'], dtype='object')

In [24]:
inputs.Age[:10]

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
5     NaN
6    54.0
7     2.0
8    27.0
9    14.0
Name: Age, dtype: float64

In [26]:
inputs.Age = inputs.Age.fillna(inputs.Age.mean())
inputs.head(5)

   Pclass   Age     Fare  female   male
0       3  22.0   7.2500   False   True
1       1  38.0  71.2833    True  False
2       3  26.0   7.9250    True  False
3       1  35.0  53.1000    True  False
4       3  35.0   8.0500   False   True

In [50]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(inputs,target,test_size = 0.2)

In [51]:
len(X_train)

712

In [52]:
len(X_test)

179

In [53]:
len(inputs)

891

In [54]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()

In [55]:
model.fit(X_train,Y_train)

GaussianNB()

In [56]:
model.score(X_test,Y_test)

0.8044692737430168

In [57]:
X_test[:10]

     Pclass        Age      Fare  female   male
538       3  29.699118   14.5000   False   True
7         3   2.000000   21.0750   False   True
739       3  29.699118    7.8958   False   True
461       3  34.000000    8.0500   False   True
215       1  31.000000  113.2750    True  False
92        1  46.000000   61.1750   False   True
471       3  38.000000    8.6625   False   True
69        3  26.000000    8.6625   False   True
224       1  38.000000   90.0000   False   True
234       2  24.000000   10.5000   False   True

In [58]:
Y_test[:10]

538    0
7      0
739    0
461    0
215    1
92     0
471    0
69     0
224    1
234    0
Name: Survived, dtype: int64

In [59]:
model.predict(X_test[:10])

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [60]:
model.predict_proba(X_test[:10])

array([[9.89438445e-01, 1.05615552e-02],
       [9.73547219e-01, 2.64527805e-02],
       [9.89342990e-01, 1.06570104e-02],
       [9.89700426e-01, 1.02995742e-02],
       [3.07046293e-04, 9.99692954e-01],
       [8.45625191e-01, 1.54374809e-01],
       [9.89776051e-01, 1.02239488e-02],
       [9.88803386e-01, 1.11966143e-02],
       [6.45210135e-01, 3.54789865e-01],
       [9.75751493e-01, 2.42485074e-02]])